[build]
  # Base directory (where package.json is located)
  base = "."
  
  # Build command (runs in the base directory)
  command = "echo 'OnPurpose Platform Build Complete' && exit 0"
  
  # Publish directory (where the built site is located)
  publish = "."
  
  # Functions directory
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200